"""Add global asset columns

Revision ID: ab3d1214609e
Revises: ffeee1bd1684
Create Date: 2026-09-06 15:38:39.380068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab3d1214609e'
down_revision: Union[str, Sequence[str], None] = 'ffeee1bd1684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('country', sa.String(), nullable=True))
    op.add_column('stocks', sa.Column('asset_type', sa.String(), nullable=True))
    op.add_column('stocks', sa.Column('currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'currency')
    op.drop_column('stocks', 'asset_type')
    op.drop_column('stocks', 'country')
    # ### end Alembic commands ###
